# -*- coding: utf-8 -*-
"""EXP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yx0f2cGFydslwFZvJMFrjAhpMs4zznV
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the uploaded image
image = cv2.imread("image1.jpg")

# Check if the image is loaded
if image is None:
    print("Error: Image not found!")
else:
    # Get image dimensions
    height, width = image.shape[:2]

    # Scale to bigger size (3x)
    scale_factor = 3.0
    bigger_image = cv2.resize(
        image,
        (int(width * scale_factor), int(height * scale_factor))
    )

    # Scale to smaller size (0.5x)
    scale_factor = 0.5
    smaller_image = cv2.resize(
        image,
        (int(width * scale_factor), int(height * scale_factor))
    )

    # Display images
    print("Original Image")
    cv2_imshow(image)

    print("Bigger Image")
    cv2_imshow(bigger_image)

    print("Smaller Image")
    cv2_imshow(smaller_image)

    # Save output images
    cv2.imwrite("Bigger_image.jpg", bigger_image)
    cv2.imwrite("Smaller_image.jpg", smaller_image)

    print("Images saved successfully.")