# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdW5XB9zflrDmnRPx2k8ejmDDwKM-IaS
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the uploaded image
img = cv2.imread('image1.jpg')

# Check whether the image is loaded
if img is None:
    print("Error: Image not found!")
else:
    # Convert to grayscale
    gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Display the grayscale image
    cv2_imshow(gray_img)

    # Save the grayscale image
    cv2.imwrite('gray_image.jpg', gray_img)

    print("Grayscale image saved successfully as gray_image.jpg")