# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RgvNoMUP5iDULYBm5PiAVNzyLi-Ja0fs
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read image
img = cv2.imread("/content/image1.jpg")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Parameters
block_sizes = [2, 3, 5]
k_values = [0.04, 0.06, 0.08]

plt.figure(figsize=(12, 10))

n = 1

for block in block_sizes:
    for k in k_values:

        # Harris Corner Detection
        corners = cv2.cornerHarris(
            np.float32(gray),
            block,
            3,
            k
        )

        # Mark detected corners
        result = img.copy()
        result[corners > 0.01 * corners.max()] = [0, 0, 255]

        # Count corners
        count = np.sum(corners > 0.01 * corners.max())

        # Display
        plt.subplot(3, 3, n)
        plt.imshow(cv2.cvtColor(result, cv2.COLOR_BGR2RGB))
        plt.title(f"Block={block}, k={k}\nCorners={count}")
        plt.axis("off")

        n += 1

plt.tight_layout()
plt.show()

print("Harris Corner Parameter Study Completed")
print("Parameters tested:")
print("Block Size:", block_sizes)
print("k Values:", k_values)