# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrzhnxgtlAmTH7bVDkT9_C3KoW-6Pw3F
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the uploaded image
img = cv2.imread('/content/image.jpg')

# Convert image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Sobel operator along X-axis
sobel_x = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)

# Sobel operator along Y-axis
sobel_y = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)

# Combine X and Y gradients
sobel_xy = cv2.magnitude(sobel_x.astype(np.float32),
                         sobel_y.astype(np.float32))

# Convert to 8-bit
sobel_xy = cv2.convertScaleAbs(sobel_xy)

# Display Original Image
print("Original Image")
cv2_imshow(img)

# Display Grayscale Image
print("Grayscale Image")
cv2_imshow(gray)

# Display Sobel XY Edge Detection
print("Sobel XY Edge Detection")
cv2_imshow(sobel_xy)