# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrzhnxgtlAmTH7bVDkT9_C3KoW-6Pw3F
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read uploaded image
img = cv2.imread('/content/image.jpg')

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Laplacian mask with positive center coefficient
laplacian_mask = np.array([
    [0, -1, 0],
    [-1, 5, -1],
    [0, -1, 0]
], dtype=np.float32)

# Apply sharpening mask
sharpened = cv2.filter2D(gray, -1, laplacian_mask)

# Display Original Image
print("Original Image")
cv2_imshow(img)

# Display Output Image
print("Sharpened Image")
cv2_imshow(sharpened)