# -*- coding: utf-8 -*-
"""EXP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdW5XB9zflrDmnRPx2k8ejmDDwKM-IaS
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the uploaded image
image = cv2.imread('image1.jpg')

# Check if the image is loaded
if image is None:
    print("Error: Image not found!")
else:
    # Apply Gaussian Blur
    blur = cv2.GaussianBlur(image, (5, 5), 10)

    # Save the blurred image
    cv2.imwrite('blurred_image.jpg', blur)

    # Display the blurred image
    cv2_imshow(blur)

    print("Blurred image saved successfully as blurred_image.jpg")