# -*- coding: utf-8 -*-
"""EXP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yx0f2cGFydslwFZvJMFrjAhpMs4zznV
"""

import cv2
from google.colab.patches import cv2_imshow
import time

# Open the uploaded video
cap = cv2.VideoCapture('video.mp4')

slow_delay = 0.10   # Slow motion delay
fast_delay = 0.02   # Fast motion delay

print("Slow Motion")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Resize frame for display
    slow_frame = cv2.resize(frame, None, fx=0.5, fy=0.5)
    cv2_imshow(slow_frame)

    time.sleep(slow_delay)

cap.release()