# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taLxqm0AWYRCkz-elcVq-mP6jkr-ncGX
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the image
img = cv2.imread('/content/image1.jpg')

# Convert image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply Canny Edge Detection
edges = cv2.Canny(gray, 100, 200)

# Display original image
print("Original Image:")
cv2_imshow(img)

# Display edge detected image
print("Canny Edge Detected Image:")
cv2_imshow(edges)

# Save the output
cv2.imwrite('/content/canny_edge.jpg', edges)