# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrzhnxgtlAmTH7bVDkT9_C3KoW-6Pw3F
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the uploaded image
img = cv2.imread('/content/image.jpg')

# Convert image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Laplacian mask with diagonal neighbors
laplacian_mask = np.array([
    [1,  1,  1],
    [1, -8,  1],
    [1,  1,  1]
], dtype=np.float32)

# Apply Laplacian mask
laplacian = cv2.filter2D(gray, cv2.CV_32F, laplacian_mask)

# Sharpen the image
sharpened = gray.astype(np.float32) - laplacian

# Convert to 8-bit image
sharpened = np.clip(sharpened, 0, 255).astype(np.uint8)

# Display Original Image
print("Original Image")
cv2_imshow(img)

# Display Grayscale Image
print("Grayscale Image")
cv2_imshow(gray)

# Display Laplacian Image
print("Laplacian Image")
cv2_imshow(cv2.convertScaleAbs(laplacian))

# Display Sharpened Image
print("Sharpened Image")
cv2_imshow(sharpened)