# -*- coding: utf-8 -*-
"""EXP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdW5XB9zflrDmnRPx2k8ejmDDwKM-IaS
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the uploaded image in grayscale
img = cv2.imread('image1.jpg', cv2.IMREAD_GRAYSCALE)

# Check if the image is loaded
if img is None:
    print("Error: Image not found!")
else:
    # Create a 5x5 kernel
    kernel = np.ones((5, 5), np.uint8)

    # Apply dilation
    dilated_img = cv2.dilate(img, kernel, iterations=1)

    # Save the output image
    cv2.imwrite('Dilated_Image.jpg', dilated_img)

    # Display the dilated image
    cv2_imshow(dilated_img)

    print("Dilated image saved successfully as Dilated_Image.jpg")