# -*- coding: utf-8 -*-
"""EXP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yx0f2cGFydslwFZvJMFrjAhpMs4zznV
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the uploaded image
image = cv2.imread("image1.jpg")

if image is None:
    print("Error: Image not found!")
else:
    cv2_imshow(image)
    print("Image displayed successfully.")