# -*- coding: utf-8 -*-
"""EXP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yx0f2cGFydslwFZvJMFrjAhpMs4zznV
"""

import cv2

# Open the webcam
cap = cv2.VideoCapture(0)

slow_factor = 0.5
fast_factor = 2.0

while True:
    ret, frame = cap.read()

    if not ret:
        break

    # Resize for slow and fast display
    slow_frame = cv2.resize(frame, None, fx=slow_factor, fy=slow_factor)
    fast_frame = cv2.resize(frame, None, fx=fast_factor, fy=fast_factor)

    # Display the frames
    cv2.imshow("Slow Motion", slow_frame)
    cv2.imshow("Fast Motion", fast_frame)

    # Press 'q' to quit
    if cv2.waitKey(30) & 0xFF == ord('q'):
        break

# Release the webcam
cap.release()
cv2.destroyAllWindows()