# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrzhnxgtlAmTH7bVDkT9_C3KoW-6Pw3F
"""

import cv2
import matplotlib.pyplot as plt
import os

# Show files available in Colab
print("Files in /content:")
print(os.listdir('/content'))

# Enter the EXACT name of your uploaded image here
image_path = '/content/image.jpg'

# Read image
img = cv2.imread(image_path)

# Check whether image was loaded successfully
if img is None:
    print("ERROR: Image not found!")
    print("Change image_path to the exact uploaded image filename.")
else:
    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Canny Edge Detection
    edges = cv2.Canny(gray, 100, 200)

    # Display images
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(edges, cmap="gray")
    plt.title("Canny Edge Detection")
    plt.axis("off")

    plt.show()