# -*- coding: utf-8 -*-
"""EXP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdW5XB9zflrDmnRPx2k8ejmDDwKM-IaS
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the uploaded image
img = cv2.imread('image1.jpg')

# Check if the image is loaded
if img is None:
    print("Error: Image not found!")
else:
    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Detect edges using Canny
    edges = cv2.Canny(gray, 100, 200)

    # Save the output image
    cv2.imwrite('Canny_Edges_3rd.jpg', edges)

    # Display the edge image
    cv2_imshow(edges)

    print("Canny edge image saved successfully as Canny_Edges_3rd.jpg")