# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taLxqm0AWYRCkz-elcVq-mP6jkr-ncGX
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the image
img = cv2.imread('/content/image1.jpg')

# Check if image is loaded
if img is None:
    print("Image not found. Please upload image1.jpg to Colab.")
else:
    # Get image dimensions
    height, width = img.shape[:2]

    # Four points from the original image
    src_points = np.float32([
        [0, 0],
        [width - 1, 0],
        [width - 1, height - 1],
        [0, height - 1]
    ])

    # Four points for the transformed image
    dst_points = np.float32([
        [50, 50],
        [width - 50, 0],
        [width - 1, height - 1],
        [0, height - 50]
    ])

    # Calculate perspective transformation matrix
    M = cv2.getPerspectiveTransform(src_points, dst_points)

    # Apply perspective transformation
    perspective_img = cv2.warpPerspective(
        img, M, (width, height)
    )

    # Display original image
    print("Original Image:")
    cv2_imshow(img)

    # Display transformed image
    print("Perspective Transformed Image:")
    cv2_imshow(perspective_img)

    # Save the output
    cv2.imwrite('/content/perspective_image.jpg', perspective_img)