# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrzhnxgtlAmTH7bVDkT9_C3KoW-6Pw3F
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the uploaded image
img = cv2.imread('/content/image.jpg')

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Blur the image
blurred = cv2.GaussianBlur(gray, (5, 5), 0)

# High-Boost Filtering
A = 2.0

# High-boost mask
high_boost = cv2.addWeighted(gray, A, blurred, -(A - 1), 0)

# Display Original Image
print("Original Image")
cv2_imshow(img)

# Display Output Image
print("High-Boost Sharpened Image")
cv2_imshow(high_boost)