# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RgvNoMUP5iDULYBm5PiAVNzyLi-Ja0fs
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read image
img = cv2.imread("/content/image1.jpg", 0)

# Illumination levels
levels = [-80, -40, 0, 40, 80]
names = ["Very Low", "Low", "Normal", "High", "Very High"]

plt.figure(figsize=(15, 15))

for i, (beta, name) in enumerate(zip(levels, names)):

    # Change brightness
    bright = cv2.convertScaleAbs(img, alpha=1, beta=beta)

    # Canny
    canny = cv2.Canny(bright, 50, 150)

    # Sobel
    sobelx = cv2.Sobel(bright, cv2.CV_64F, 1, 0, ksize=3)
    sobely = cv2.Sobel(bright, cv2.CV_64F, 0, 1, ksize=3)
    sobel = cv2.convertScaleAbs(cv2.magnitude(sobelx, sobely))

    # Prewitt
    px = cv2.filter2D(bright, -1, np.array([[-1,0,1],[-1,0,1],[-1,0,1]]))
    py = cv2.filter2D(bright, -1, np.array([[-1,-1,-1],[0,0,0],[1,1,1]]))
    prewitt = cv2.convertScaleAbs(cv2.magnitude(
        px.astype(float), py.astype(float)))

    # Laplacian
    laplacian = cv2.convertScaleAbs(
        cv2.Laplacian(bright, cv2.CV_64F)
    )

    # Display
    results = [bright, canny, sobel, prewitt, laplacian]
    titles = [
        f"{name} Illumination",
        "Canny",
        "Sobel",
        "Prewitt",
        "Laplacian"
    ]

    for j in range(5):
        plt.subplot(5, 5, i * 5 + j + 1)
        plt.imshow(results[j], cmap="gray")
        plt.title(titles[j])
        plt.axis("off")

plt.tight_layout()
plt.show()