# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taLxqm0AWYRCkz-elcVq-mP6jkr-ncGX
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import files

# Upload video
uploaded = files.upload()

# Get uploaded video filename
video_name = next(iter(uploaded))

# Open the video
cap = cv2.VideoCapture(video_name)

# Check if video is opened
if not cap.isOpened():
    print("Error: Could not open video.")
else:
    # Get video dimensions
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS)

    # Four points from the original video frame
    src_points = np.float32([
        [0, 0],
        [width - 1, 0],
        [width - 1, height - 1],
        [0, height - 1]
    ])

    # Four destination points
    dst_points = np.float32([
        [50, 50],
        [width - 50, 0],
        [width - 1, height - 1],
        [0, height - 50]
    ])

    # Calculate perspective transformation matrix
    M = cv2.getPerspectiveTransform(src_points, dst_points)

    # Create output video
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(
        '/content/perspective_video.mp4',
        fourcc,
        fps,
        (width, height)
    )

    # Process video frame by frame
    while True:
        ret, frame = cap.read()

        if not ret:
            break

        # Apply perspective transformation
        transformed_frame = cv2.warpPerspective(
            frame, M, (width, height)
        )

        # Write transformed frame
        out.write(transformed_frame)

    # Release resources
    cap.release()
    out.release()

    print("Perspective transformation completed!")