# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RgvNoMUP5iDULYBm5PiAVNzyLi-Ja0fs
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read image
img = cv2.imread("/content/image1.jpg", 0)

# Add Gaussian noise
noise = np.random.normal(0, 25, img.shape)
noisy = np.clip(img + noise, 0, 255).astype(np.uint8)

# ORB detection
orb = cv2.ORB_create()
kp_orb = orb.detect(noisy, None)
orb_img = cv2.drawKeypoints(noisy, kp_orb, None)

# SIFT detection
sift = cv2.SIFT_create()
kp_sift = sift.detect(noisy, None)
sift_img = cv2.drawKeypoints(noisy, kp_sift, None)

# Display results
plt.figure(figsize=(12, 4))

plt.subplot(1, 3, 1)
plt.imshow(img, cmap="gray")
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(orb_img, cmap="gray")
plt.title(f"ORB Features: {len(kp_orb)}")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(sift_img, cmap="gray")
plt.title(f"SIFT Features: {len(kp_sift)}")
plt.axis("off")

plt.tight_layout()
plt.show()

print("ORB Keypoints:", len(kp_orb))
print("SIFT Keypoints:", len(kp_sift))