# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrzhnxgtlAmTH7bVDkT9_C3KoW-6Pw3F
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the uploaded image from Colab Files
img = cv2.imread('/content/image.jpg')

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Sobel operator along X-axis
sobel_x = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)

# Convert result to 8-bit
sobel_x = cv2.convertScaleAbs(sobel_x)

# Display Original Image
print("Original Image")
cv2_imshow(img)

# Display Grayscale Image
print("Grayscale Image")
cv2_imshow(gray)

# Display Sobel X Edge Detection
print("Sobel X Edge Detection")
cv2_imshow(sobel_x)