# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrzhnxgtlAmTH7bVDkT9_C3KoW-6Pw3F
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the uploaded image
img = cv2.imread('/content/image.jpg')

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Gradient masks
Gx = np.array([
    [-1, -2, -1],
    [ 0,  0,  0],
    [ 1,  2,  1]
], dtype=np.float32)

Gy = np.array([
    [-1,  0,  1],
    [-2,  0,  2],
    [-1,  0,  1]
], dtype=np.float32)

# Apply gradient masks
gradient_x = cv2.filter2D(gray, cv2.CV_32F, Gx)
gradient_y = cv2.filter2D(gray, cv2.CV_32F, Gy)

# Calculate gradient magnitude
gradient = cv2.magnitude(gradient_x, gradient_y)

# Normalize gradient
gradient = cv2.normalize(gradient, None, 0, 255, cv2.NORM_MINMAX)

# Add gradient mask to original image
sharpened = cv2.addWeighted(
    gray.astype(np.float32), 1.0,
    gradient.astype(np.float32), 1.0,
    0
)

# Convert to 8-bit
sharpened = np.clip(sharpened, 0, 255).astype(np.uint8)

# Display Original Image
print("Original Image")
cv2_imshow(img)

# Display Output Image
print("Gradient Masking Sharpened Image")
cv2_imshow(sharpened)