# -*- coding: utf-8 -*-
"""EXP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yx0f2cGFydslwFZvJMFrjAhpMs4zznV
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the uploaded image
img = cv2.imread("image1.jpg")

# Check if the image is loaded
if img is None:
    print("Error: Image not found!")
else:
    # Rotate clockwise (90 degrees)
    clockwise = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)

    # Rotate counter-clockwise (90 degrees)
    counterclockwise = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)

    # Display images
    print("Original Image")
    cv2_imshow(img)

    print("Clockwise Rotated Image")
    cv2_imshow(clockwise)

    print("Counter-Clockwise Rotated Image")
    cv2_imshow(counterclockwise)

    # Save the rotated images
    cv2.imwrite("clockwise_image.jpg", clockwise)
    cv2.imwrite("counterclockwise_image.jpg", counterclockwise)

    print("Images saved successfully.")