# -*- coding: utf-8 -*-
"""EXP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdW5XB9zflrDmnRPx2k8ejmDDwKM-IaS
"""

import cv2
from google.colab.patches import cv2_imshow

# Read the uploaded image
img = cv2.imread('image1.jpg')

# Check if the image is loaded
if img is None:
    print("Error: Image not found!")
else:
    # Convert the image to grayscale
    gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Create a 5x5 rectangular kernel
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))

    # Apply erosion
    eroded_image = cv2.erode(gray_image, kernel, iterations=1)

    # Save the eroded image
    cv2.imwrite('eroded_image.jpg', eroded_image)

    # Display the eroded image
    cv2_imshow(eroded_image)

    print("Eroded image saved successfully as eroded_image.jpg")