# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taLxqm0AWYRCkz-elcVq-mP6jkr-ncGX
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the image
img = cv2.imread('/content/image1.jpg')

# Check if image is loaded
if img is None:
    print("Image not found. Please upload image1.jpg to Colab.")
else:
    rows, cols = img.shape[:2]

    # Affine transformation matrix
    M = np.float32([
        [1, 0, 100],
        [0, 1, 50]
    ])

    # Apply affine transformation
    affine_img = cv2.warpAffine(img, M, (cols, rows))

    # Display original image
    print("Original Image:")
    cv2_imshow(img)

    # Display transformed image
    print("Affine Transformed Image:")
    cv2_imshow(affine_img)

    # Save the output
    cv2.imwrite('/content/affine_image.jpg', affine_img)