# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taLxqm0AWYRCkz-elcVq-mP6jkr-ncGX
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read image
img = cv2.imread('/content/image1.jpg')

# Resize image
img = cv2.resize(img, (480, 270))

rows, cols = img.shape[:2]

# Source points
src = np.float32([
    [0, 0],
    [cols - 1, 0],
    [cols - 1, rows - 1],
    [0, rows - 1]
])

# Destination points
dst = np.float32([
    [0, 0],
    [cols - 1, 0],
    [cols - 1, rows - 1],
    [0, rows - 1]
])

# Homography matrix
H = cv2.getPerspectiveTransform(src, dst)

# Apply transformation
result = cv2.warpPerspective(img, H, (480, 360))

# Show original image
print("Original Image:")
cv2_imshow(img)

# Show transformed image
print("Homography Transformed Image:")
cv2_imshow(result)

# Save output
cv2.imwrite('/content/homography_image.jpg', result)